const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.EightDir,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.SetLayoutEffectEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{title: 0},
	{mansion: 0},
	{titleplayer: 0},
	{Sine: 0},
	{playy: 0},
	{about: 0},
	{abouttitle: 0},
	{paper: 0},
	{lore: 0},
	{nextAbout: 0},
	{Solid: 0},
	{wallWood: 0},
	{redWool: 0},
	{Keyboard: 0},
	{lostObject1: 0},
	{smoothStone: 0},
	{isMendapatkanLostObject: 0},
	{"8Direction": 0},
	{Flash: 0},
	{player: 0},
	{endingStage1: 0},
	{vindicator: 0},
	{evoker: 0},
	{Bullet: 0},
	{Fade: 0},
	{evoker_fangs: 0},
	{lostObject2: 0},
	{endingStage2: 0},
	{healthBar: 0},
	{endingStage3: 0},
	{lostObject3: 0},
	{healthInject: 0},
	{lostObject4: 0},
	{endingStage4: 0},
	{endingStage5: 0},
	{lostObject5: 0},
	{health: 0},
	{daBoss: 0},
	{skill1: 0},
	{skill2: 0},
	{skill3: 0},
	{bossbar: 0},
	{daBossProjectile: 0},
	{ammoText: 0},
	{sensor: 0},
	{fred: 0},
	{Audio: 0},
	{joystickBG: 0},
	{DragDrop: 0},
	{joysticDrag: 0},
	{dist: 0},
	{joysticJoystic: 0},
	{healthinject: 0},
	{ammo: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	title: class extends self.ITextInstance {},
	mansion: class extends self.ISpriteInstance {},
	titleplayer: class extends self.ISpriteInstance {},
	playy: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	abouttitle: class extends self.ITextInstance {},
	paper: class extends self.ITiledBackgroundInstance {},
	lore: class extends self.ITextInstance {},
	nextAbout: class extends self.ISpriteInstance {},
	wallWood: class extends self.ISpriteInstance {},
	redWool: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	lostObject1: class extends self.ISpriteInstance {},
	smoothStone: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	endingStage1: class extends self.ISpriteInstance {},
	vindicator: class extends self.ISpriteInstance {},
	evoker: class extends self.ISpriteInstance {},
	evoker_fangs: class extends self.ISpriteInstance {},
	lostObject2: class extends self.ISpriteInstance {},
	endingStage2: class extends self.ISpriteInstance {},
	healthBar: class extends self.ISpriteInstance {},
	endingStage3: class extends self.ISpriteInstance {},
	lostObject3: class extends self.ISpriteInstance {},
	healthInject: class extends self.ISpriteInstance {},
	lostObject4: class extends self.ISpriteInstance {},
	endingStage4: class extends self.ISpriteInstance {},
	endingStage5: class extends self.ISpriteInstance {},
	lostObject5: class extends self.ISpriteInstance {},
	daBoss: class extends self.ISpriteInstance {},
	skill1: class extends self.ISpriteInstance {},
	skill2: class extends self.ISpriteInstance {},
	skill3: class extends self.ISpriteInstance {},
	bossbar: class extends self.ITextInstance {},
	daBossProjectile: class extends self.ISpriteInstance {},
	ammoText: class extends self.ITextInstance {},
	sensor: class extends self.ISpriteInstance {},
	fred: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	joystickBG: class extends self.ISpriteInstance {},
	joysticDrag: class extends self.ISpriteInstance {},
	joysticJoystic: class extends self.ISpriteInstance {}
}